### ISSUE TITLE
Does not play well with html template

### ISSUE THREAD

**Issue by changwuf31** [pk-fr/yakpro-po#1]
Particularlarly html template with inline php code inside

**Comment by pk-fr** [comment]
Updated README.md with:

Note: This tool has been written to obfuscate pure php sources.  
it is not intended to be used with html and embeded php inside.

**Comment by pk-fr** [comment]
You can still embed html within php using the echo <<<END ... END; syntax!

**Comment by changwuf31** [comment]
Ah.. Thanks for the tip :+1:

**Comment by Ten0** [comment]
Hello,
I would like to know if you have any suggestion as to how we could hence convert these mixed html/php files to pure php files (I mean, not manually) before putting them through your tool, since many of the things we may want to obfuscate, as users of this tool, contains mixed html and php.
