### ISSUE TITLE
Change shebang and permissions of yakpro-po.php

### ISSUE THREAD

**Issue by mologie** [pk-fr/yakpro-po#10]
Hello,

the main file's shebang points to `/usr/bin/php`. This is not the convention and will cause trouble on systems with multiple PHP installations, especially because the output of the script depends on the PHP environment and its installed addons.

Please change the first line to `#!/usr/bin/env php` so that the shell's active PHP version is used.

Your README file also specifies that the main PHP file should be made executable. Right now, every pull on my *nix platforms results in a conflict due to incorrect permissions, so that I have to revert permissions before pulling/merging. Why not include the correct permissions with the git repository right away? On *nix, just chmod +x and `git add` the file again. On Windows, the `git update-index --chmod=+x yakpro-po.php` command would have the same effect because there is no executable bit on Windows.

Cheers, Oliver

**Comment by pk-fr** [comment]
Thanks... I learned something... 
I didn't knew about   *#!/usr/bin/env php*   shebang abilities ... 
I made some googling to learn more about...  
Concerning the +x permission, I was using the github web interface (with its nice visual diff) to commit... 
I switched to command line...  
version 1.8.4 includes those changes!

**Comment by mologie** [comment]
Thanks, and I wish you happy holidays!
