### ISSUE TITLE
Error:  Wrong version of PHP-Parser detected!

### ISSUE THREAD

**Issue by Joker-jar** [pk-fr/yakpro-po#101]
Actual version of PHP-Parser in GitHub is 5.x. So setup steps doesn't work. You should use

`git clone https://github.com/nikic/PHP-Parser.git --branch 4.x`

instead of:

`git clone https://github.com/nikic/PHP-Parser.git`

**Comment by pk-fr** [comment]
thanx a lot, I do not follow PHP-Parser everyday lol
README.md reflects now your issue and your solution
