### ISSUE TITLE
Modification date doesn't change

### ISSUE THREAD

**Issue by reza55n** [pk-fr/yakpro-po#103]
Hi and thank you for this useful program!
I use Wampserver on Windows 10. As obfuscated files' modification date are the same as original files' date, server sometimes runs old, un-obfuscated files instead of new file and because it's a server-side caching, clearing browser's cache doesn't have anything with fixing this problem. Thanks!

**Comment by pk-fr** [comment]
unobfuscated and obfuscated files are not within the same directory.
if you really ned to have them at the same place, you can either disable opcache or restart apache
