### ISSUE TITLE
Decode - Clear All Goto Statement Video

### ISSUE THREAD

**Issue by lamquocdat** [pk-fr/yakpro-po#118]
I found this video in Youtube.
They can decode PHP after obfuscating?
link youtube: https://www.youtube.com/watch?v=DVmaHklmHII&t=121s

**Comment by pk-fr** [comment]
Impossible to have back variable names or function names or comments that are lost during obfuscation process...
( variable names or functions names can be retrieved only on the machine that obfuscated the code and where the sources are...  so it is useless lol)
