### ISSUE TITLE
Config file setting now working as expected

### ISSUE THREAD

**Issue by ocgltd** [pk-fr/yakpro-po#122]
I would like to exclude a single file from being obfuscated (just copy the file as is to the destination directory).  I have the setting below, and the path is right, but it's still being obfuscated.  Why?

`$conf->t_keep                           = ['/myproject/settings.php']; `

I have also tried:

`$conf->t_keep                           = array('/myproject/settings.php'); `

**Comment by pk-fr** [comment]
are you sure the path is right?
/myproject/settings.php   is at the root of the filesystem....

do you really want the leading /  of the path ?

**Comment by ocgltd** [comment]
Yes, it's a full absolute path.  I cut the file path and issued "ls /myproject/settings.php" and it found the file no problem.

Are entries for this setting relative to the source path?

**Comment by pk-fr** [comment]
I tested, and you are right, it does not work with absolute paths...
yakpro-po explores subdirectories and filtes relatively to the project directory...
try with 
$conf->t_keep                           = ['settings.php'];

**Comment by ocgltd** [comment]
Ok I will change to relative path.  And I assume 'project directory' is synonymous with 'source directory', not directory with the cnf file is
