### ISSUE TITLE
yakpro breaks jquery

### ISSUE THREAD

**Issue by ocgltd** [pk-fr/yakpro-po#123]
I'm trying to run my php code through yakpro-po, and for some reason it breaks the code (won't display in browser().  Browser reports :

jquery is not defined
$ is not defined
and a few more...

I tried disabling EVERY option in the cnf file, and still the code is broken.  If publish the php files WITHOUT running through yakpro, they work fine in the browser.

Am I missing something obvious?  (I can 't be the first person to hit this issue)

**Comment by pk-fr** [comment]
jquery is javascript, not php !

refer to sections 
* note
* YOU MUST BE AWARE OF THE FOLLOWING
* Hints for preparing your Software to be run obfuscated


obfuscate only standalone projects : no libraries and no plugins of another php framework...
no php included in html but only pure php files...
no indirect call, etc.

**Comment by ocgltd** [comment]
oh...:)  I embed javascript in my php.  Sounds like your tools won't work for me.  I was use POBS before, which worked great, but after upgrading to PHP8 it completely broke.

Looks like I have to find another tool.  Too bad the parser can't just re-insert the javascript as is....
