### ISSUE TITLE
Undefined function directory_remove

### ISSUE THREAD

**Issue by cabloo** [pk-fr/yakpro-po#18]
In includes/functions.php there are references to a `directory_remove` function which doesn't exist in PHP. Is it supposed to be `rmdir`? I'm not sure if that one is recursive or not.

**Comment by cabloo** [comment]
Oh, it's supposed to be `remove_directory` (which is created in that file).

**Comment by pk-fr** [comment]
you are right, it was remove_directory...
thanks, fixed now!
