### ISSUE TITLE
Doesnt work with composer autoload

### ISSUE THREAD

**Issue by Tom29** [pk-fr/yakpro-po#20]
Getting this error:

> Fatal error: Uncaught exception 'LogicException' with message 'Passed array does not specify an existing static method (class 'ComposerAutoloaderInit6abcfcd8de4a38fce2851d378ca1a6d0' not found)' in /var/www/domain/web/library/vendor/composer/autoload_real.php:8
> Stack trace:
> #0 /var/www/domain/web/library/vendor/composer/autoload_real.php(8): spl_autoload_register(Array, true, true)
> #1 /var/www/domain/web/library/vendor/autoload.php(8): uUBET::gbBbi()
> #2 /var/www/domain/web/base/init.php(8): include('/var/www/domain...')
> #3 /var/www/domain/web/index.php(8): require('/var/www/domain...')
> #4 {main}
>   thrown in /var/www/domain/web/library/vendor/composer/autoload_real.php on line 8

I believe it's relevant with this one: https://github.com/pk-fr/yakpro-po/issues/13

**Comment by pk-fr** [comment]
Same issue same answer:

I do not have time nor will to deal with any third party product...

If you are able to provide a **generic _yakpro-po.cnf_** file for composer, wordpress, ... or whatever other third party product, I will be very happy to provide a link to your repository...

**Comment by Tom29** [comment]
Can you explain to use `t_keep` and `t_skip` i've tried to put vendor / composer directory for avoid obfuscating but didn't work.

`t_keep = ['./library/vendor']`

Are they absolute or relative path?

**Comment by pk-fr** [comment]
`$conf->t_keep   = ['./library/vendor'];` 
is ok... (if you have php >=5.4 ... otherwise use array('') syntax )  but I think that you will also have to populate $conf->t_ignore_classes , $conf->t_ignore_methods, ... and so on...

**Comment by Tom29** [comment]
@pk-fr i've tried it, but the script still obfuscates the code inside the vendor folder.
i tried with both absolute and relative path, in both t_keep vs t_skip , and didn't work

**Comment by pk-fr** [comment]
@Tom29 relative paths are relative to the current working directory (the diretcory on which you are ) when you run yakpro-po...
It works as I use it on my own big project I wrote the obfuscator for...
the relating extract of my yakpro-po.cnf is the following:
```
$conf->source_directory             = '.';
$conf->target_directory             = '..';

$conf->t_keep                       = array('config.php','local','memo','3rdparty/ckeditor');
$conf->t_skip                       = array('00_RELEASE_00','mppksag');
```
and my current working directory is the projects root directory when i run the yakpro-po command

**Comment by Tom29** [comment]
@pk-fr i just found the way to correct here.
the path needed to be 'library/vendor' instead of using absolute path.
if i ignored vendor folder, do i need to declare to ignore all classes, methodes, properties names ... of all classes inside the vendor path?

**Comment by pk-fr** [comment]
@Tom29 you have to ignore all classes, methodes, properties names ...
that you use within your project....

**Comment by pk-fr** [comment]
if you want to make a generic yakpro-po.cnf that will be usable to others, you will have to declare and maintain everything...

**Comment by Tom29** [comment]
@pk-fr yeah, i know. i'm making a cnf files thinking about writing some script which can get all the classes, methods, properties inside one folder.

or simply disable naming obfustation for all of them. Because some properties inside that folder can match with many other classes of mine.

**Comment by Tom29** [comment]
Hey, how's about `t_ignore_pre_defined_classes` ? If i put all the class name in vendor folder to it, will it work?

**Comment by pk-fr** [comment]
by default:
`$conf->t_ignore_pre_defined_classes     = 'all'; `
you do not need to change it unless you want to obfuscate method names that are defined in a pre-defined class that you do not use...

**Comment by Phil795** [comment]
To use composer it is necessary not to change the namespace references, or to adapt each namespace consiquently.

I have a configuration for composer, but adapted to Laravel

**Comment by pk-fr** [comment]
good news...
If you publish it on GitHub, I will provide a link to your repository.

**Comment by Phil795** [comment]
I will release a basic version for composer and one for laravel in the course of next week. Let you know when it's online :-)

**Comment by Connum** [comment]
@Phil795 did this ever happen? ;)

**Comment by Phil795** [comment]
> @Phil795 did this ever happen? ;)

I'm afraid not. Switched to another payment solution in the same week. 

But I still have the config for Composer in a project. 

If the Composer configuration is sufficient for you, I can send it to you

**Comment by Connum** [comment]
That would be great, thanks!

**Comment by oualid13** [comment]
Hello,

Any news about the composer config?

Thanks

**Comment by Phil795** [comment]
Unfortunately, I can no longer find the configuration.

But I can show you how you can easily create it

With this function you can print out all used namespaces. Build the output so that an array with the absolute namespaces is created and copy them into the config at `$conf->t_ignore_namespaces`.
```php
    public function getNamespaces()
    {
      $namespaces=array();
      foreach(get_declared_classes() as $name) {
          if(preg_match_all("@[^\\\]+(?=\\\)@iU", $name, $matches)) {
              $matches = $matches[0];
              $parent =&$namespaces;
              while(count($matches)) {
                  $match = array_shift($matches);
                  if(!isset($parent[$match]) && count($matches))
                      $parent[$match] = array();
                  $parent =&$parent[$match];
              }
          }
      }
      print_r($namespaces);
    }
```

Hope it helps you
