### ISSUE TITLE
Cannot obfuscate simple WordPress plugin

### ISSUE THREAD

**Issue by baptx** [pk-fr/yakpro-po#24]
I cannot obfuscate a simple WordPress plugin (like https://wordpress.org/plugins/disable-google-fonts/) with your tool but it works with other tools (like https://github.com/naneau/php-obfuscator).

In `/var/www/html/wordpress/wp-content/plugins`, I execute `~/Downloads/yakpro-po/yakpro-po.php disable-google-fonts -o disable-google-fonts-dev`

I don't know if we need to keep the files generated in the folder `yakpro-po`, so I tried to keep them (I got a fatal error message when I tried without keeping the folder).

To keep the `yakpro-po` folder structure, I created a main file `disable-google-fonts.php` in the folder `disable-google-fonts-dev` with these basic informations to load the WordPress plugin:

```
<?php
/**
 * Plugin Name: Disable Google Fonts Dev
 */

require_once 'yakpro-po/obfuscated/disable-google-fonts.php';
```

When I try to activate the plugin in the WordPress admin area, I still get the error message (there is no function named `WeIzo` in the original plugin, it looks like an obfuscated name):

> Fatal error: Uncaught Error: Call to undefined function WeIzo() in /var/www/html/wordpress/wp-content/plugins/disable-google-fonts-dev/yakpro-po/obfuscated/disable-google-fonts.php:8 Stack trace: #0 /var/www/html/wordpress/wp-content/plugins/disable-google-fonts-dev/yakpro-po/obfuscated/disable-google-fonts.php(8): DcYMB->__construct() #1 /var/www/html/wordpress/wp-content/plugins/disable-google-fonts-dev/disable-google-fonts.php(6): require_once('/var/www/html/w...') #2 /var/www/html/wordpress/wp-admin/includes/plugin.php(1897): include('/var/www/html/w...') #3 /var/www/html/wordpress/wp-admin/plugins.php(172): plugin_sandbox_scrape('disable-google-...') #4 {main} thrown in /var/www/html/wordpress/wp-content/plugins/disable-google-fonts-dev/yakpro-po/obfuscated/disable-google-fonts.php on line 8

Edit: my copy-paste of the error message referenced several unrelated issues because of the '#' character, I don't know if we can avoid this.

**Comment by pk-fr** [comment]
yakpro-po has been designed to obfuscate standalone projects only !!!.

if you use external libraries, you have to obfuscate also the libray, and modify it in order to make it run obfuscated...
if your program is a Library/plugin of another Software/Framework,
the you have to modify/port the external Software/Framework source code in order to obfuscate it and have it run obfuscated.
you have also to maintain a specific yakpro-po.cfg whith all things that are not to be obfuscated across each new version of the external Software/Framework
 
see: 
-  YOU MUST BE AWARE OF THE FOLLOWING:  in README.md
-  See Hints for preparing your Software to be run obfuscated section of README.md


If you want to create and maintain a yakpro-po.cfg specific to WordPress plugins 
( I think that it is hard work ),
I will put a link to your github repository ...

**Comment by baptx** [comment]
Ok, I saw the readme but it would be nice I you have an idea where the error comes from or how to make your obfuscator work with a WordPress plugin because there was no problem when I used the other obfuscator I shared above (without additional configuration for the plugin I shared). The WordPress plugin repository is not mine but I took this plugin as an example because it is a simple one with a few lines of code, all in one file.

**Comment by pk-fr** [comment]
the other obfuscator only obfuscates variable names...  
disable all the other obfuscation and you will get the same behavior...

When I was looking for a good obfuscator for obfuscating my own big standalone project, I tested naneau but I found that it was very poor obfuscated... so I decided to write my own.
it now fits all my needs, and I put it on github for other users that have same expectations...

feel free to fork it and adapt it to your own needs!!!

**Comment by baptx** [comment]
Thanks for your reply, I managed yo get your obfuscator working by disabling some obfuscation.

I set obfuscate_function_name to false in yakpro-po.cnf because I was using classes / methods only and needed several WordPress function names without obfuscation. I also had to disable obfuscation for some names used by WordPress in t_ignore_constants, t_ignore_variables and t_ignore_classes.

Adding a value in t_ignore_variables to ignore a variable obfuscation was not enough because this WordPress variable used internal properties like `$bp->loggedin_user->id`. So I had to set obfuscate_property_name to false. Is it possible to automatically disable obfuscation of all properties of a variable that was added in t_ignore_variables?

Do you know if it is possible to obfuscate a PHP callback? I had to set obfuscate_method_name to false because the method was obfuscated but not the callback which is an array with a string like `[$this, 'methodName']`.
Also, is it possible to only obfuscate private methods, like the other PHP obfuscator does?

Obfuscating code can be useful for freelance projects until we get paid entirely. Can we disable the obfuscator comment generated at the beginning of PHP files? The less informations there is, the better the obfuscation is :)

**Comment by pk-fr** [comment]
it is impossible with only syntax analysis when you call a method to know if it is private or not...
you need to have a full semantic analysis which is a huge job that does not provide PHP-Parser...

> Also, is it possible to only obfuscate private methods, like the other PHP obfuscator does?

**Comment by baptx** [comment]
I see, do you have an idea for my other questions?

**Comment by Connum** [comment]
@baptx could you post a full config working for WordPress?

**Comment by baptx** [comment]
@Connum I don't have it anymore and it may depend on your setup. You should be able to make it work with the details I mentioned in a previous comment, I explained all the changes I made. Of course you should only obfuscate a plugin and not the entire WordPress system, which could cause a lot of issues.

**Comment by Connum** [comment]
Thanks a lot!
