### ISSUE TITLE
Run the obfuscated project

### ISSUE THREAD

**Issue by karmac2015** [pk-fr/yakpro-po#31]
How can I run the obfuscated project in wamp server ? is there any loader like other obfuscation tools  zend, ioncube , source guardien ?

**Comment by pk-fr** [comment]
there is no loader...
obfuscated programs are pure php ones..

just use obfuscated files instead of original ones !

**Comment by karmac2015** [comment]
Can I add php files to obfuscated directory manually ?

**Comment by pk-fr** [comment]
if you do that they will be deleted on re-obfuscation...
you can use $conf->t_keep  configuration parameter  to not obfuscate a list of files...

**Comment by karmac2015** [comment]
Error: your use of define() function is not compatible with yakpro-po!
 Only 2 parameters, when first is a literal string is allowed...
Can you help me to solve this error please. I am trying to use your tool to obfuscate my **Yii2** project

**Comment by pk-fr** [comment]
just read the message....
you use the define()  function having either 1st parameter not a string litteral  ( I.e. "a string" ) or more than 2 parameters..
this use is not compatible with the obfuscator... change your source code.

**Comment by karmac2015** [comment]
After excluding vendor directory that contains all external libraries and extensions the project has been obfuscated successfully but the following error appear when I trying to run my project : 
Fatal error: Uncaught LogicException: Passed array does not specify an existing static method (class 'ComposerAutoloaderInit31f8ee465cdf32e540f6c3d6d131a877' not found) in C:\wamp64\www\my-project\yakpro-po\obfuscated\vendor\composer\autoload_real.php on line 8

**Comment by pk-fr** [comment]
see readme.md

yakpro-po has been developed for standalone projects only!

I do not support any Framework, nor symphony, nor composer.
Please feel free to provide a specific yakpro-po.cnf excluding all composer features when you have successfully done one.

**Comment by karmac2015** [comment]
Ok, thank you I wish you support framework like Yii2.

**Comment by pk-fr** [comment]
I do not, and will never support  any Framework.
If you make and support a specific yakpro-po.cnf file for a specific Framework, and put it on github, I will provide a link to your repository!

**Comment by karmac2015** [comment]
Ok, I will try but till know a lot of errors appear when I try to run my project

**Comment by pk-fr** [comment]
try to not obfuscate class names nor  class methods.... 
all autoload or magic features of Frameworks are not compatible with obfuscation... 
the Framework will not know how to load things with obfuscated names...
