### ISSUE TITLE
PHP Notice:  A non well formed numeric value encountered in /usr/local/yakpro-po/include/check_version.php on line 25

### ISSUE THREAD

**Issue by ahkmunna** [pk-fr/yakpro-po#34]
At the end by running this command

`yakpro-po --help`

The error:

`PHP Notice:  A non well formed numeric value encountered in /usr/local/yakpro-po/include/check_version.php on line 25
PHP Stack trace:
PHP   1. {main}() /usr/local/yakpro-po/yakpro-po.php:0
PHP   2. require_once() /usr/local/yakpro-po/yakpro-po.php:20

Notice: A non well formed numeric value encountered in /usr/local/yakpro-po/include/check_version.php on line 25

Call Stack:
    0.0009     371808   1. {main}() /usr/local/yakpro-po/yakpro-po.php:0
    0.0039     382688   2. require_once('/usr/local/yakpro-po/include/check_version.php') /usr/local/yakpro-po/yakpro-po.php:20

Error:	Wrong version of PHP-Parser detected!
Currently, only 4.x branch of PHP-Parser is supported!
	You can try to use the following command:
	# git clone https://github.com/nikic/PHP-Parser.git
`

**Comment by pk-fr** [comment]
solved in 2.0.1 version...
thanx
