### ISSUE TITLE
Problem with use of eval

### ISSUE THREAD

**Issue by Wizard2k** [pk-fr/yakpro-po#35]
Hi guy, 
first of all thank you for your work.

I have a problem and hope you can help me.

I use the eval functions in some place of my code and when I try to obfuscate it doesn't word:

`<?php

function funcTest($param)
{
    return "hey! " . $param;
}

$sFuncToCall = "funcTest";
$sParam = "hello world";
eval("\$sReturnFunction = " . $sFuncToCall . "(\"" . $sParam . "\");");

echo $sReturnFunction;

?>`

and here you can find obfuscated version:

`<?php

function funcTest($A92PuKiSftPYqqd)
{
return "\150\x65\171\x21\x20" . $A92PuKiSftPYqqd;
}
$ZvHkE9gCbvdtEZE = "\x66\x75\x6e\143\x54\x65\163\x74";
$JNc7kjLDMCgghbp = "\x68\x65\x6c\x6c\x6f\40\x77\157\x72\x6c\x64";
eval("\x24\x73\x52\x65\x74\165\x72\x6e\106\165\156\x63\x74\151\x6f\156\x20\x3d\x20" . $ZvHkE9gCbvdtEZE . "\x28\x22" . $JNc7kjLDMCgghbp . "\42\x29\73");
echo $HvGn14hkJPjuMtz;

?>`

**Comment by pk-fr** [comment]
see "Hints for preparing your Software to be run obfuscated" of readme.md :

> if you obfuscate functions, do not use indirect function calls like
>     $my_var = 'my_function';
>     $my_var();
> or put all the function names you call indirectly in the $conf->t_ignore_functions array!
> 
> 
> Do not use indirect variable names!
>     $$my_var = something;
> or put all the variable names you use indirectly in the $conf->t_ignore_variables array!

**Comment by Wizard2k** [comment]
Hi Pascal, 
thank you very much! It works!

Regards Roberto

**Comment by pk-fr** [comment]
Please star it  if you like it :p

**Comment by Wizard2k** [comment]
Sure!

👍

**Comment by pk-fr** [comment]
thanx :)
