### ISSUE TITLE
Scrambled labels might match reserved words

### ISSUE THREAD

**Issue by biziclop** [pk-fr/yakpro-po#39]
Hi, thanks for the nice project! :)

I set `$conf->scramble_length = 2;` to make things smaller (and I'm just experimenting anyways), but PHP complained:  
`PHP Parse error:  syntax error, unexpected 'aS' (T_AS), expecting identifier (T_STRING)`

This was the show-stopping expression:  
`goto aS;`

While $-prefixed variable names are not affected, labels, class names, constants, etc. won't really like if they are renamed for reserved words. 

Maybe a reserved word list should be included ( http://php.net/reserved )?

**Comment by pk-fr** [comment]
Hi, thanks for reporting the bug...

case sensitive elements were incorrectly tested against reserved tokens.
( "As" was tested as "As" not as "as" )

fixed in version 2.0.3
