### ISSUE TITLE
outer classes/methods should not be encoded

### ISSUE THREAD

**Issue by Antoine321** [pk-fr/yakpro-po#4]
example:
- new stdClass() : should not be encoded as it's not declared in the source folder (it's a standard class)
- DomDocument::{whatever constant} : should not be encoded, as the DomDocument class is not declared in the source folder (standard class)

Until that is resolved, I have to deactivate obfuscation for classes and methods.
Well, I know it's minor glitches, overall good job !

**Comment by pk-fr** [comment]
Thank's for having tested it!
You're absolutly right!!!
I've forgotten predefined classes .... as well as predefined interfaces (there is no predefined traits yet)
I will correct it  as soon as I have some time 
I will release a new version next  week-end If I do not find any time before.
I hope you will star this project  afterwards...
Best regards,
Pascal

**Comment by pk-fr** [comment]
Hi Antoine,

I just published 1.8.0 release
a new config file $conf->t_ignore_pre_defined_classes element, replaces the old $conf->t_ignore_module_methods.

all pre-defined classes, class constants, properties, and methods are now not obfuscated by default.

Cheers,
Pascal
