### ISSUE TITLE
Issues scrambling php scripts

### ISSUE THREAD

**Issue by dipixx** [pk-fr/yakpro-po#40]
Hi, I'm testing your software on php scripts that can be launched on the command line. On these scripts there seem to be an issue because this code:

`#!/usr/bin/php`
`<?php
echo "123";
?>`

becomes this (comments stripped out)

`<?php
 echo "\43\x21\57\x75\163\x72\x2f\142\x69\x6e\57\x70\x68\x70\12"; echo "\61\62\x33";
`
where \43\x21\57\x75\163\x72\x2f\142\x69\x6e\57\x70\x68\x70\12 is #!/usr/bin/php
instead of 

`#!/usr/bin/php`
`<?php
echo "\61\62\x33";
?>`

Am I doing anything wrong?

**Comment by pk-fr** [comment]
thanx for bug report :)
at this moment the obfuscator works only for code starting with <?php
it is a very good enhancement!
I will take a look at it as soon as I have time.
best regards

**Comment by pk-fr** [comment]
fixed in 2.0.4 release...
thanx for your support!
please star the project if you like it :)
