### ISSUE TITLE
Does not obfuscate string value

### ISSUE THREAD

**Issue by nickcartery** [pk-fr/yakpro-po#41]
Trying with your demo, after decoding in unphp.net, I still can see "hello", "that's it!".... I used **--obfuscate-string-literal**, but It does not work :|
```

<?php
/*--------------------------
    simple test program !
---------------------------*/
$hello      = "hello ";
$world      = "world ";
$what       = "what ";
$a          = "a ";
$beautiful  = "beautiful ";
$day        = "day ";

for($i=0;$i<=7;++$i)        // small loop!
{
    echo $hello;    echo $world;                                echo PHP_EOL;
    echo $what;     echo $a;    echo $beautiful;    echo $day;  echo PHP_EOL;
}
echo "that's it!".PHP_EOL;
?>
```

**Comment by pk-fr** [comment]
as you can easily see in the demo, the checkbox to obfuscate string litterals is labeled:
"String literals (pseudo obfuscation)"
each character is replaced randomly either by it's value, octal value or hex value.
unphp (or other progs) can easily go back to string values.
it is not the same with the other (not pseudo) obfuscation features...
