### ISSUE TITLE
PHP file not usable anymore after obfuscation

### ISSUE THREAD

**Issue by jiahao42** [pk-fr/yakpro-po#42]
Hello, thank you so much for your amazing tool.

I met a problem with your tool: I am trying to obfuscate some php webshell using your tool for research purpose. I tried to obfuscate [this file](https://github.com/JohnTroony/php-webshells/blob/master/php-backdoor.php) using the default setting of your tool, and then the obfuscated file is not working. Do you have any idea why?

Thanks a lot.

**Comment by pk-fr** [comment]
Hi jiahao42,

Your file does not start by 
<?php

but by <?
