### ISSUE TITLE
Suggestion: option to follow symlinks

### ISSUE THREAD

**Issue by biziclop** [pk-fr/yakpro-po#44]
Hi, sometimes it would be useful to follow symlinks instead of replicating them. Maybe only when the output directory is specified.
`yakpro-po source_directory -o target_directory`

Currently I commented out the `if (is_link($source_path)) …` block in  
https://github.com/pk-fr/yakpro-po/blob/f5e43ac3c5ac43591026dc2041fbfc376e38e722/include/functions.php#L228  
to achieve this. :)

Thanks!

**Comment by pk-fr** [comment]
Hi,

I personally  don't need such a behaviour, but if someone needs it, it'a a good idea to implement an option for this.
I do not have any time for now, I will do it on september...

thanx,
Pascal

**Comment by pk-fr** [comment]
option added in version 2.0.5
