### ISSUE TITLE
Bug: Function definition in "parse" time instead of execution time

### ISSUE THREAD

**Issue by lucasexe** [pk-fr/yakpro-po#46]
If I have this code:

a.php:
```php
function f() {
  echo 'test';
}
include('b.php');
```

b.php:
```php
if (!function_exists('f')) {
   function f() {
       echo 'test2';
   }
}
```
When the option `shuffle_stmts` is enabled, the definition of `f()` in `b.php` will be appear out of the `if`, therefore the php interpreter will try to define the function in "parse" time instead of execution time, and this will throw the error below:

```
PHP Fatal error:  Cannot redeclare f() in b.php on line 2
```

Maybe we can just add an `if (true)` in these situations.

**Comment by pk-fr** [comment]
cannot reproduce...
