### ISSUE TITLE
Newbie.. PHP parser no correctly installed

### ISSUE THREAD

**Issue by rafaelberzunza** [pk-fr/yakpro-po#47]
Hi, I installed PHP-Parser as indicated at xampp\parser\ folder vía composer. I extracted yakpro-po.zip in that folder as directed but seems not to work. ¿How can I get it done? I'm running windows 8.

**Comment by lucasexe** [comment]
The PHP-Parser must be installed inside yakpro-po folder.

Example:
yakpro-po -> C:\xampp\yakpro-po
PHP-Parser -> C:\xampp\yakpro-po\PHP-Parser

**Comment by rafaelberzunza** [comment]
Thanks a lot it works.

Clumsy me
