### ISSUE TITLE
Issues with php 7.4

### ISSUE THREAD

**Issue by alekseyp** [pk-fr/yakpro-po#50]
I know php7.4 is still not released but I wanted to share an issue I'm facing. (works well with other PHP versions)

```Exception ParseError:syntax error, unexpected 'FN' (T_FN), expecting identifier (T_STRING)```

In my particular case, I'm runnign it as:

```yakpro-po/yakpro-po.php  --scramble-length 2 --scramble-mode identifier --no-obfuscate-namespace-name --no-obfuscate-method-name --no-obfuscate-property-name --no-obfuscate-trait-name --no-obfuscate-interface-name --no-obfuscate-class-name --no-obfuscate-class_constant-name --no-obfuscate-constant-name --no-obfuscate-function-name```

**Comment by alekseyp** [comment]
`FN` is a reserved word in php7.4 now and should be excluded.

**Comment by pk-fr** [comment]
thanks for your early report...
fixed in 2.0.6
