### ISSUE TITLE
Detected as virus after obfuscation

### ISSUE THREAD

**Issue by amainyebriggs** [pk-fr/yakpro-po#51]
after obfuscation, during upload on web server its detected as a virus .
![Screenshot from 2019-11-21 22-49-41](https://user-images.githubusercontent.com/13424678/69379839-88145500-0cb1-11ea-9f79-b6ee450af230.png)

**Comment by pk-fr** [comment]
either your file is a virus before obfuscation, either your web server detects false positives...
it is not an issue of yakpro-po!
