### ISSUE TITLE
manual install

### ISSUE THREAD

**Issue by X25guru** [pk-fr/yakpro-po#53]
I have php-parser installed via composer and I can't get yakpro to see it properly. I don't want to load the 9000 files required by git. If you can provide a basic outline of where things need to be it would be helpful

**Comment by pk-fr** [comment]
yakpro-po is framework agnostic and does not make use of composer or any third party software...

PHP-Parser directory is expected to be a subdirectory of yakpro-po.... (see line 17 of yakpro-po.php... you can even modify it for yourself but you will have to do it again for each new release)

You can try to put a symlink to where composer has installed it... but without any waranty of any kind
