### ISSUE TITLE
Use namespace doesn't get excluded

### ISSUE THREAD

**Issue by andthink** [pk-fr/yakpro-po#54]
`use Tbuy_Flow_Model_Storage_Factory as StorageFactory;`
becomes
` use fNSeU as StorageFactory;
`
even if I've set 

`$conf->obfuscate_namespace_name         = false; `

Am I doing something wrong?
This is my whole config file
https://gist.github.com/andthink/672fbd8d3d854617b16f604c1a918bc7

**Comment by oualid13** [comment]
i think that for this you have to put "Tbuy_Flow_Model_Storage_Factory" and "StorageFactory" in the t_ignore_namespaces array

**Comment by pk-fr** [comment]
fixed with release 2.0.7
