### ISSUE TITLE
Code shuffler moves use keyword after class instantiation

### ISSUE THREAD

**Issue by mologie** [pk-fr/yakpro-po#6]
Test case:

```php
<?php
echo "a";
use FooNamespace\BarClass;
echo "b";
BarClass::foo();
echo "c";
echo "d";
echo "e";
```

Example obfuscated output:

```
$ yakpro-po --silent --shuffle-statements --no-obfuscate-namespace-name --no-obfuscate-class-name --no-obfuscate-string-literal testScramblerUse.php
```
```php
<?php
 goto eRjJL; eRjJL: echo 'a'; goto bMybk; jYOQK: echo 'c'; goto RLpd3; s61kw: echo 'b'; goto N2256; N2256: BarClass::U_97n(); goto jYOQK; RLpd3: echo 'd'; goto V30rC; bMybk: use FooNamespace\BarClass; goto s61kw; V30rC: echo 'e';
```

While the order of execution is correct, PHP actually does not execute the `use` statement, but interpret it statement-by-statement while generating bytecode for the function. It will select the wrong class for the bytecode and everything will go haywire.

For the sake of completeness, here is a test class which will show that the above code indeed does not run properly. Add an include line for it right after the `<?php` of each code snippet.
```php
// BarClass.php
<?php
namespace FooNamespace;
class BarClass {
  public static function foo() {
    echo "foo";
  }
}
```

**Comment by pk-fr** [comment]
Hi Oliver,

in the new 1.8.0 release,
if a use statement is present, we do not shuffle statements that are located before the last use statement.
