### ISSUE TITLE
run with php 7.4  occur `PHP Deprecated: Array and string offset access syntax with curly braces is deprecated`

### ISSUE THREAD

**Issue by mkanako** [pk-fr/yakpro-po#62]
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /Tools/yakpro-po/yakpro-po.php on line 74

Deprecated: Array and string offset access syntax with curly braces is deprecated in /Tools/yakpro-po/yakpro-po.php on line 74

PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /Tools/yakpro-po/include/check_version.php on line 28
PHP Stack trace:
PHP   1. {main}() /Tools/yakpro-po/yakpro-po.php:0

Deprecated: Array and string offset access syntax with curly braces is deprecated in /Tools/yakpro-po/include/check_version.php on line 28

Call Stack:
    0.0023     414744   1. {main}() /Tools/yakpro-po/yakpro-po.php:0

PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /Tools/yakpro-po/include/classes/scrambler.php on line 378
PHP Stack trace:
PHP   1. {main}() /Tools/yakpro-po/yakpro-po.php:0

Deprecated: Array and string offset access syntax with curly braces is deprecated in /Tools/yakpro-po/include/classes/scrambler.php on line 378

Call Stack:
    0.0023     414744   1. {main}() /Tools/yakpro-po/yakpro-po.php:0

PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /Tools/yakpro-po/include/classes/scrambler.php on line 378
PHP Stack trace:
PHP   1. {main}() /Tools/yakpro-po/yakpro-po.php:0

Deprecated: Array and string offset access syntax with curly braces is deprecated in /Tools/yakpro-po/include/classes/scrambler.php on line 378

.....

**Comment by pk-fr** [comment]
thanks,
fixed in 2.0.9

**Comment by mkanako** [comment]
https://github.com/pk-fr/yakpro-po/blob/da8637b48cad70cf2da10e8acf018b4c76790147/include/classes/parser_extensions/my_pretty_printer.php#L22

miss this line 
thx!

**Comment by pk-fr** [comment]
thx! 
hope this is ok now!

**Comment by mkanako** [comment]
yes, now is working great!
