### ISSUE TITLE
How to use after installation

### ISSUE THREAD

**Issue by 27443114** [pk-fr/yakpro-po#65]
How do you use it after installation? I am a novice
![捕获](https://user-images.githubusercontent.com/44933758/77630852-aef7d600-6f86-11ea-99e1-6537355c85e0.PNG)

**Comment by pk-fr** [comment]
Not supported on windows, but you can try  :
`php yakpro-po.php`

**Comment by 27443114** [comment]
Here are some tips

Info:   Using [C:\Users\Administrator\Desktop\yakpro-po\yakpro-po.cnf] Config File...
Info:   yakpro-po version = 2.0.10
Error:  source_directory and target_directory not specified!
        neither within command line parameter,
        nor in config file!

**Comment by pk-fr** [comment]
So it is working as expected!

please refer to **Usage** section ( and **Other command line options** section ) of readme.md...

**Comment by 27443114** [comment]
How to use it? I still don't understand

**Comment by pk-fr** [comment]
`php yakpro-po source_filename -o target_filename`
or
`php yakpro-po source_directory -o target_directory`

`yakpro-po --help` for more options

**Comment by 27443114** [comment]
![捕获](https://user-images.githubusercontent.com/44933758/77633106-f0d64b80-6f89-11ea-9913-d859fb06c4c2.PNG)
Prompt these

**Comment by pk-fr** [comment]
sorry forget that you where en windows...
`php yakpro-po.php source_filename -o target_filename`
or
`php yakpro-po.php source_directory -o target_directory`

`php yakpro-po.php --help` for more options

source_filename is the source path of the file you want to obfuscate and target_filename the target path of the file that will contain the obfuscated file

**Comment by 27443114** [comment]
OK, I've got it. Thank you, writer. Have a good life

**Comment by pk-fr** [comment]
thanx, please star it if you like it ;)
