### ISSUE TITLE
Use keyword is not processed correctly

### ISSUE THREAD

**Issue by mologie** [pk-fr/yakpro-po#7]
Test case:

```php
<?php
use FooNamespace\BarClass;
BarClass::fooMethod();
```

Example output:

```php
<?php
 use Ursex\edPAQ as eDpAq; lhk21::n0Qum();
```

I would have expected the obfuscator to emit `eDpAq::n0Qum();` as function call instead. Some implementation for aliasing classes appears to be there already since an 'as' is appended to the 'use' statement, but it doesn't do the right thing just yet.

**Comment by pk-fr** [comment]
Hi Oliver,

in the new 1.8.0 release,
namespaces and classes are now sharing the same obfuscation context in order to be alias compliant.

**Comment by mologie** [comment]
Thanks for the three quick fixes, use and constants work properly now.
