### ISSUE TITLE
Compatibility check for defined() should take into account ignored variables

### ISSUE THREAD

**Issue by sedimentation-fault** [pk-fr/yakpro-po#76]
During obfuscation of some PHP script, I got the dreaded error:

```
        Error: your use of defined() function is not compatible with yakpro-po!
        Only 1 literal string parameter is allowed...
```

And I say _dreaded_ because it forces me to exclude the whole file from obfuscation - and this forces me to exclude the whole library the file belongs to - and this forces me to find and exclude all functions, objects etc I use from this library.

In moments like this, one becomes creative...so I had a look at the code of the script I wanted to obfuscate. :-)

The code in the script that causes the above error in _yakpro-po_ looks like this:

```
foreach ($inputarr as $val) {
...
         else if (($val === null) || (!defined($val)))
...
}
```

so the problem is using the variable _$val_ as parameter to the _defined()_ function. Creative as I had to be, I decided to add _$val_ to the _$conf->t_ignore_variables_ of my _.cnf_ file. However, the error persisted.

This is a bug.

### Proposed solution

The error is produced at around line 490 of 

_yakpro-po.d/include/classes/parser_extensions/my_node_visitor.php_

```
if ($fn_name=='define') throw new Exception("Error: your use of $fn_name() function is not compatible with yakpro-po!".PHP_EOL."\tOnly 2 parameters, when first is a literal string is allowed...");
                            else                    throw new Exception("Error: your use of $fn_name() function is not compatible with yakpro-po!".PHP_EOL."\tOnly 1 literal string parameter is allowed...");
```

At that point, _yakpro-po_ should check  if _$arg_ is of type variable. If it is, it should check if   _$arg->name_  is listed in _$conf->t_ignore_variables_, or if any of the prefixes in _$conf->t_ignore_variables_prefix_ match the start of _$arg->name_. If so, it should NOT issue the error.

The same kind of check can possibly be done for other types than 'variable'.

In any of the above cases, one need not issue an error and can safely proceed to obfuscation because the passed parameter (_$arg->name_) is excluded from obfuscation, being either an excluded variable, or some other excluded object.

### Further enhancements

I also propose to change the messages from

`Only XXXXXX is allowed...`

to

`Only XXXXXX is allowed...You use: $arg->name`

so that it becomes clear _which_ invocation of _define()_ resp. _defined()_ causes the problem.

**Comment by pk-fr** [comment]
This is not a bug: see **Hints for preparing your Software to be run obfuscated** section of Readme.md
as you cannot use indirect variables with variable obfuscation or indirect function calls with function obfusctaion, you cannot use indirect constants with constant obfuscation.

It is impossible at obfuscation time to know what content value will be within the variable and so to obfuscate it's value...

Either you change your code using only string litterals,
either you disable constant obfuscation! 
`$conf->obfuscate_constant_name          = false;`

**Comment by sedimentation-fault** [comment]
> It is impossible at obfuscation time to know what content value will be within the variable and so to obfuscate it's value...

Yes, it is impossible to know - but this is not the point. The point is, if I _already added_ what is in _$arg->name_ to my array of variables to ignore, then why is _yakpro-po_ complaining? It can just as well continue its job on the file with the settings I gave it and it will not destroy anything (currently it will 'stop on error' and I don't want to change this behavior just for this).

Since _$val_ is excluded from obfuscation in my _yakpro-po.cnf_ and _defined()_, being a PHP function, will not be obfuscated anyway, the code

```
foreach ($inputarr as $val) {
...
         else if (($val === null) || (!defined($val)))
...
}
```

will not be destroyed by obfuscation. _yakpro-po_ can check that _$val_ is a variable and is one that should not be obfuscated, so it knows at obfuscation time that _defined($val)_ will not be touched and _$val_ will not be touched too - so all is OK. Am I wrong?

**Comment by pk-fr** [comment]
even if $val is excluded from obfuscation, it's content value is not known by the obfuscator! and cannot be scrambled to match the scrambled value when the constant was (or not) defined!

so disable constant obfuscation if you still want to use it!

**Comment by pk-fr** [comment]
refer to https://www.php.net/manual/en/function.defined
and it's **Note**

**Comment by sedimentation-fault** [comment]
> even if $val is excluded from obfuscation, it's content value is not known by the obfuscator! and cannot be scrambled to match the scrambled value when the constant was (or not) defined!
> 
> so disable constant obfuscation if you still want to use it!

Oh...now I see. This is a very fine point that I missed. I was concentrating on variables all the time, but _$val_ will evaluate to a constant at run time (since its value is passed to defined() for a check) and this will interfere with constant obfuscation! Wow...

Theoretically, if I knew the exact values that _$val_ can assume at run time, or at least a common start string, I could put those into _$conf->t_ignore_constants_, resp. _$conf->t_ignore_constants_prefix_ - but if I knew them, I could just as well change the code to use only string literals in _defined()_, as you say...

Thank you!
