### ISSUE TITLE
Better Setup for Windows pls

### ISSUE THREAD

**Issue by KeinWeb** [pk-fr/yakpro-po#82]
I have issues with setup this tool on windows cause i dont know how to create an symbolic link to this php file.
Maybe someone can help me.

**Comment by mostafa2142** [comment]
same ,
i wish it had setup explanation for windows too

**Comment by pk-fr** [comment]
yakpro-po has been developped on linux and  I never tested it (and I never will) under  windows …

However, I tried to not use linux specific functions…
I think that it should be possible to run it under windows without major changes… 
( Some people tell me that they managed to make it work on Windows)

I think that it should be possible to run it under windows without major changes… but without any warranty..
After having install php-cli,
-	First, delete the 1st line of yakpro-po.php
(#!/usr/bin/env php (specific linux/unix)
-	Run it by prefixing the command line by the php.exe path: 
/php_install_path/php.exe yakpro-po.php options……

I recommand you to install a linux VM or use Windows Subsystem for Linux with bash installed.
and then, follow linux instructions
