### ISSUE TITLE
Error when requiring a php file

### ISSUE THREAD

**Issue by mostafa2142** [pk-fr/yakpro-po#85]
so i finally managed to install linux mint and i obfuscate my php files successully ,
but the problem is that when i send a http request to my php file (to test if they work with the new obfuscator)
it throws these errors : 
Warning: require(qIbEN): failed to open stream: No such file or directory
Fatal error: require(): Failed opening required 'qIbEN' (include_path='.;C:\php\pear')
Warning: Use of undefined constant qIbEN - assumed 'qIbEN'

so any idea where why im getting these errors ?

**Comment by pk-fr** [comment]
see the warning : use of an undefined constant !
