### ISSUE TITLE
Adding an option to ignore Global Variables.

### ISSUE THREAD

**Issue by peyman-mohamadpour** [pk-fr/yakpro-po#87]
Global Variables should be considered as an ignore too. Please consider adding an option.

**Comment by pk-fr** [comment]
global keyword make a variable global at runtime within a function
it can be placed everywhere, also just before return instruction and with no effect with the local variable with the same name before.
cannot be determined at  obfuscation time.

**Comment by peyman-mohamadpour** [comment]
So what should I do with global vars? Any suggestions?

**Comment by pk-fr** [comment]
**$conf->t_ignore_variables = ['var1','var2', ...];** for all variables you want to ignore
