### ISSUE TITLE
ignore $this->class->functionName();

### ISSUE THREAD

**Issue by xguntis** [pk-fr/yakpro-po#88]
How to ignore functionName(s)? I need to ignore all that starts with $this->...

**Comment by pk-fr** [comment]
use **$conf->t_ignore_methods = [ 'fn1','fn2',...]** to put all the function names you want to ignore.

**Comment by xguntis** [comment]
does that mean i cant ignore all that begin with $this->myclass? i need to enter all function names one by one, correct?

**Comment by pk-fr** [comment]
yes...
if all your functions have the same prefix  or a few common prefixes you can use the  $conf->t_ignore_methods_prefix array

**Comment by xguntis** [comment]
thanks for great tool and fast responses!
