### ISSUE TITLE
double $ get the PHP Notice: Undefined variable

### ISSUE THREAD

**Issue by oohook** [pk-fr/yakpro-po#90]
When i run the target code ,i got the PHP Notice: Undefined variable  hello in xxx.

source code
`
$hello = 'yakpro';
$yakpro = 'hello';
echo $$yakpro;
`

I found a way to fixed it, in the yakpro-po.cnf to set the t_ignore_variables like this
`
$conf->t_ignore_variables = ['hello'];
`

Any other solution in the feature? @pk-fr

**Comment by pk-fr** [comment]
please refer to "**Hints for preparing your Software to be run obfuscated**" section of [README.md](https://github.com/pk-fr/yakpro-po/blob/master/README.md)

```
Do not use indirect variable names!
    $$my_var = something;
or put all the variable names you use indirectly in the $conf->t_ignore_variables array!
```
