### ISSUE TITLE
failure on define

### ISSUE THREAD

**Issue by X25guru** [pk-fr/yakpro-po#92]
The statement:
          $foo = 'FOO';
          define($foo, 'BAR');

Error: your use of define() function is not compatible with yakpro-po!
	Only 2 parameters, when first is a literal string is allowed...

Is there a workaround for this? an ignore? To have a whole project fail for this is quite frustrating.

**Comment by kwoods1911** [comment]
Did you find a solution to this issue ? I am having the same error.

**Comment by X25guru** [comment]
The workaround is to change your defines or to use global variables instead. As you can see the project is a black hole in terms of support so you kind of have to fit your code around it. Itt was a while ago so I don't remember exactly but I think I converted to global variables. It was a PIA but once dont the thing works well
