### ISSUE TITLE
yakpro-po: command not found

### ISSUE THREAD

**Issue by 27443114** [pk-fr/yakpro-po#95]
[root@VM-8-6-centos yakpro-po]# yakpro-po --help
-bash: yakpro-po: command not found

How to solve this problem? I have followed the steps

**Comment by pk-fr** [comment]
perhaps you misse step 7. Create a symbolic link in the /usr/local/bin directory
or perhaps you have installed yakpro-po in another directory or perhaps /usr/local/bin is not in your PATH env ...
