### ISSUE TITLE
labels are not obfuscated

### ISSUE THREAD

**Issue by EddieKidiw** [pk-fr/yakpro-po#97]
My script.
&lt;?php
goto a;
echo 'Foo';
a:
echo 'Bar';
?>

After obfuscated
&lt;?php
/*   __________________________________________________
    |  Obfuscated by YAK Pro - Php Obfuscator  2.0.12  |
    |              on 2021-08-22 12:57:16              |
    |    GitHub: https://github.com/pk-fr/yakpro-po    |
    |__________________________________________________|
*/
 goto EAkS2; EAkS2: **goto a;** goto UYo0o; UYo0o: echo "\106\x6f\x6f"; goto i2fwf; i2fwf: **a:** goto yGhS3; yGhS3: echo "\102\x61\x72";

i found the label function in include/classes/parser _extensions/my_node visitor.php online 806 \$name = \$node->name; and add name \$name = \$node->name->name; and it worked for me 🙏

**Comment by EddieKidiw** [comment]
![yakpro](https://user-images.githubusercontent.com/35423587/130357403-ac93b376-51fb-469a-ac73-f4c1c6f01011.png)

**Comment by pk-fr** [comment]
Thanx for your report, issue is now corrected in 2.0.13 release
