### ISSUE TITLE
Include file to use constatnt

### ISSUE THREAD

**Issue by ankitnetsol** [pk-fr/yakpro-po#98]
Hello,

   I have to create a constant file with the use of yakpro-po and include and use that file. So how can I use that file?

E.g.  
test.php
define('FORNT_APP_PATH', "google.com");

I have to use this FORNT_APP_PATH constant in another file So how can I use that.

Please give me a reply as soon as possible.

Thanks.

**Comment by pk-fr** [comment]
not a yakpro-po issue
refer to your php manual
